# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moms Kitchen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  #pod 'TwitterKit'
  # Pods for Moms Kitchen

  pod 'LGSideMenuController'
  pod 'AlamofireImage', '~> 3.3'
  pod 'IQKeyboardManagerSwift', '5.0.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod  'GoogleSignIn'
  pod 'LinkedinSwift', '~> 1.6.6'
end
