# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MIShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MIShop
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'IQKeyboardManagerSwift', '5.0.0'
  #pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'LGSideMenuController'
  pod 'TextFieldEffects'
  pod 'ImageSlideshow', '~> 1.6'
  pod 'IQKeyboardManagerSwift', '~> 5.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
end
