# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Explore Local' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Explore Local

  pod 'LGSideMenuController'
  pod 'AlamofireImage', '~> 3.3'
  pod 'IQKeyboardManagerSwift', '5.0.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod  'GoogleSignIn'
  pod 'LinkedinSwift' #, '~> 1.6.6'
  pod 'Cosmos', '~> 15.0'
  pod 'GooglePlaces'
  # pod 'FacebookShare'
  #pod 'CHTCollectionViewWaterfallLayout/Swift'
  pod 'ImageSlideshow', '~> 1.6'
  pod "ImageSlideshow/Alamofire"
  pod 'Stripe'
end
