# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Luxongo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Luxongo
#pod 'DTOverlayController', path => 'https://github.com/tungvoduc/DTOverlayController.git'
    pod 'FacebookLogin'
    pod 'GoogleSignIn'
    pod 'LinkedinSwift'
    pod 'AlamofireImage'
    pod 'IQKeyboardManagerSwift'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'ImageSlideshow'
    pod "ImageSlideshow/Alamofire"
end


#- FBSDKCoreKit, 5.2.1
#- FBSDKLoginKit, 5.2.1
#- FacebookCore, 0.7.0
#- FacebookLogin, 0.7.0

#Installing GTMSessionFetcher (1.2.2)
#Installing GoogleSignIn (4.4.0)
#Installing GoogleToolboxForMac (2.2.1)

#Installing IOSLinkedInAPIFix (2.0.4)
#Installing LinkedinSwift (1.7.9)

#Installing Alamofire (4.8.2)
#Installing AlamofireImage (3.5.2)

#Installing GoogleMaps 3.1.0
