# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Happenings' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AlamofireImage', '~> 3.3'
  pod 'IQKeyboardManager'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'GooglePlaces' 
  pod 'PuiSegmentedControl'
  pod 'LGSideMenuController'
  pod ‘SwiftRangeSlider’
  pod "ImageSlideshow/Alamofire"
  pod 'Cosmos'
  pod 'ImageSlideshow'
end
