# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LevelShoes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LevelShoes

pod 'SwiftyGif'
pod 'AlamofireImage'
pod 'SwiftyJSON'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'MBProgressHUD', '~> 1.2.0'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'IQKeyboardManagerSwift', '5.0.0'
pod 'DTTextField'
pod 'STPopup'
pod 'ReachabilitySwift'
pod 'RangeSeekSlider','~> 1.7.0'
pod 'SDWebImage'
pod 'MASegmentedControl'
pod 'DropDown'
pod 'BottomPopup', '~> 0.5.5'
pod 'SkeletonView'
pod 'SwiftSVG'
pod 'CryptoSwift'
pod 'ElasticSwift', '~> 1.0.0-alpha.11'
pod 'ElasticSwiftCore', '~> 1.0.0-alpha.11'
pod 'ElasticSwiftQueryDSL', '~> 1.0.0-alpha.11'
pod 'ElasticSwiftCodableUtils', '~> 1.0.0-alpha.11'
pod 'ElasticSwiftNetworking', '~> 1.0.0-alpha.11'
pod 'Frames','~> 3.0'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Adjust', '~> 4.23.1'
pod 'MarketingCloudSDK', '~> 7.2'
pod 'Firebase/Database'
end
