# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def shared_pods
  pod 'Bluuur'
  pod 'SDWebImage'
  pod 'MaterialComponents'
  pod 'Fabric'
  pod 'TagCellLayout'
  pod 'Crashlytics'
  pod 'MagicalRecord'
  pod 'UIColor+MLPFlatColors'
  pod 'LoremIpsum'
  pod 'MaterialShowcase'
  pod 'google-cast-sdk'
  pod 'GoogleSignIn'
  pod 'GoogleAds-IMA-iOS-SDK'
  pod 'Google-Mobile-Ads-SDK'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'CleverTap-iOS-SDK'
  pod 'FreshchatSDK'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'PubNub'
  pod 'Cosmos', '~> 23.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'SwiftKeychainWrapper'
end




target 'OTT' do

  use_frameworks!
  
  shared_pods
end


target 'FirstShows' do
  use_frameworks!
  shared_pods
end

target 'Aastha' do
  use_frameworks!
  shared_pods
end
target 'GoTV' do
  use_frameworks!
  shared_pods
end
target 'yvs' do
  use_frameworks!
  shared_pods
end

target 'Tsat' do
  use_frameworks!
  shared_pods
end

target 'Mobitel' do
  use_frameworks!
  shared_pods
end

target 'supposetv' do
  use_frameworks!
  shared_pods
end

target 'pbns' do
  use_frameworks!
  shared_pods
end

target 'AirtelSL' do
  use_frameworks!
  shared_pods
end

target 'gac' do
  use_frameworks!
  shared_pods
end

target 'ViusasaRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end

target 'FirstShowsRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end


target 'AasthaRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end
target 'GoTVRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end
target 'yvsRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end

target 'TsatRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end

target 'mobitelRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end

target 'supposetvRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end

target 'pbnsRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end


target 'AirtelSLRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end



target 'gacRichPush' do
  use_frameworks!
  platform :ios, '10.0'
  pod "CTNotificationService"
end

inhibit_all_warnings!
