# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Carry Partner' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carry Partner

  pod 'FacebookCore'
pod 'FacebookLogin'
pod 'GoogleSignIn'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'SwiftWebSocket'

pod 'Firebase/Core'
pod 'Firebase/Messaging'

# Utility
pod 'SlideMenuControllerSwift'
pod 'HCSStarRatingView'
pod 'SwiftGifOrigin', '~> 1.6.1'
#pod 'LinearProgressBarMaterial'
pod 'LinearProgressView'
pod 'DropDown'
pod 'IQKeyboardManager'

# Networking
pod 'Alamofire'
pod 'AlamofireImage'

end
