# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XPhorm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XPhorm

  pod 'AlamofireImage'
  pod 'IQKeyboardManagerSwift'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod  'GoogleSignIn'
  pod 'LinkedinSwift'
  pod 'Cosmos'
  pod 'GooglePlaces'
  pod 'ImageSlideshow'
  pod 'JTAppleCalendar'
  pod 'MBProgressHUD'
  #, '~> 1.6'
  #pod 'LGSideMenuController'
  # pod 'FSCalendar'
  pod "ImageSlideshow/Alamofire"
  
end
