# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThumbPin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift', '5.0.8'
  pod 'AlamofireImage', '~> 3.3'
  pod 'Alamofire', '~> 4.4'
  pod 'GooglePlaces'
  pod 'iOSDropDown'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'LGSideMenuController'
  pod 'GoogleMaps'
  pod 'FSPagerView', '~> 0.7.2'
  pod 'HSCycleGalleryView', '~> 1.1.0'
  pod 'ReverseExtension', '~> 0.5'
  pod 'Cosmos', '~> 16.0'
  pod 'Google-Mobile-Ads-SDK'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod  'GoogleSignIn'
  pod 'LinkedinSwift'
  # Pods for ThumbPin

end
