# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Carry' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Carry

   pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'GoogleSignIn'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'SwiftWebSocket'
    
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    
    # Utility
    pod 'SlideMenuControllerSwift'
    pod 'HCSStarRatingView'
    pod 'SwiftGifOrigin', '~> 1.6.1'
    pod 'IQKeyboardManagerSwift'
    pod 'Toast-Swift', '~> 3.0.1'
    pod 'LinearProgressBarMaterial'
    #pod 'GifMagic'
    #pod 'SAMKeychain'
    
    # Payment
    #pod 'PayPal-iOS-SDK'
    
    # Networking
    pod 'Alamofire'
    pod 'AlamofireImage'

  target 'CarryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
