// Generated by Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
#ifndef OTTSDK_SWIFT_H
#define OTTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="OTTSdk",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


SWIFT_CLASS("_TtC6OTTSdk3API")
@interface API : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk9YuppModel")
@interface YuppModel : NSObject
- (NSString * _Nonnull)getImageUrlWithValue:(id _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)safeValueForKeyWithKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class Details;

SWIFT_CLASS("_TtC6OTTSdk8APIError")
@interface APIError : YuppModel
@property (nonatomic, readonly) NSInteger code;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, strong) Details * _Nullable details;
@property (nonatomic, readonly) NSInteger actionCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (APIError * _Nonnull)defaultError SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC6OTTSdk6APILog")
@interface APILog : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AdUrlTypes;

SWIFT_CLASS("_TtC6OTTSdk13AdUrlResponse")
@interface AdUrlResponse : YuppModel
@property (nonatomic, copy) NSString * _Nonnull adConfigName;
@property (nonatomic, copy) NSArray<AdUrlTypes *> * _Nonnull adUrlTypes;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class Position;

SWIFT_CLASS("_TtC6OTTSdk10AdUrlTypes")
@interface AdUrlTypes : YuppModel
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic, copy) NSString * _Nonnull adUnitId;
@property (nonatomic, strong) Position * _Nonnull position;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<AdUrlTypes *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

@class NSCoder;

SWIFT_CLASS("_TtC6OTTSdk13AnalyticsInfo")
@interface AnalyticsInfo : YuppModel <NSCoding>
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nonnull dataKey;
@property (nonatomic, copy) NSString * _Nonnull dataType;
@property (nonatomic) int32_t id;
@property (nonatomic, copy) NSString * _Nonnull customData;
@property (nonatomic, copy) NSString * _Nonnull packageType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk10AppManager")
@interface AppManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk10Attributes")
@interface Attributes : YuppModel <NSCoding>
@property (nonatomic, copy) NSString * _Nonnull currency;
@property (nonatomic, copy) NSString * _Nonnull displayLanguage;
@property (nonatomic, copy) NSString * _Nonnull timezone;
@property (nonatomic, copy) NSString * _Nonnull grade;
@property (nonatomic, copy) NSString * _Nonnull board;
@property (nonatomic, copy) NSString * _Nonnull email_id;
@property (nonatomic, copy) NSString * _Nonnull email_notification;
@property (nonatomic, copy) NSString * _Nonnull iit_jee_neet_application_no;
@property (nonatomic, copy) NSString * _Nonnull selected_lang_codes;
@property (nonatomic, copy) NSString * _Nonnull targeted_exam;
@property (nonatomic, copy) NSString * _Nonnull lms_user_id;
@property (nonatomic, copy) NSString * _Nonnull lms_user_name;
@property (nonatomic, copy) NSString * _Nonnull lms_password;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk6Banner")
@interface Banner : YuppModel
@property (nonatomic, copy) NSString * _Nonnull subtitle;
@property (nonatomic) BOOL isInternal;
@property (nonatomic, copy) NSString * _Nonnull buttonText;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Banner *> * _Nonnull)bannersWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk6CCData")
@interface CCData : YuppModel
@property (nonatomic, copy) NSString * _Nonnull language;
@property (nonatomic, copy) NSString * _Nonnull filePath;
@property (nonatomic, copy) NSString * _Nonnull fileType;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class Display;
@class Metadata;
@class TemplateData;

SWIFT_CLASS("_TtC6OTTSdk4Card")
@interface Card : YuppModel
@property (nonatomic, strong) Display * _Nonnull display;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable hover;
@property (nonatomic, strong) Metadata * _Nonnull metadata;
@property (nonatomic, copy, getter=template, setter=setTemplate:) NSString * _Nonnull template_;
@property (nonatomic, strong) TemplateData * _Nonnull templateData;
@property (nonatomic) NSInteger adPositionIndex;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Card *> * _Nonnull)cardsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

@class TVGuideDisplay;
@class Program;

SWIFT_CLASS("_TtC6OTTSdk10ChannelObj")
@interface ChannelObj : YuppModel <NSCopying>
@property (nonatomic, strong) TVGuideDisplay * _Nonnull display;
@property (nonatomic, strong) Metadata * _Nonnull metadata;
@property (nonatomic) NSInteger channelID;
@property (nonatomic, copy) NSArray<Program *> * _Nonnull programs;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<ChannelObj *> * _Nonnull)channelObjsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk23ChannelProgramsResponse")
@interface ChannelProgramsResponse : YuppModel
@property (nonatomic) NSInteger channelId;
@property (nonatomic, copy) NSArray<Program *> * _Nonnull programs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<ChannelProgramsResponse *> * _Nonnull)channelProgramsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk12ClientConfig")
@interface ClientConfig : YuppModel
@property (nonatomic) NSInteger bannersPerPageMaxLimit;
@property (nonatomic) NSInteger catchupTvMaxDays;
@property (nonatomic) NSInteger contentLanguagesMaxLimit;
@property (nonatomic) NSInteger livetvChannelsMaxLimit;
@property (nonatomic, copy) NSString * _Nonnull primaryTimeZone;
@property (nonatomic, copy) NSString * _Nonnull primaryTimeZoneOffset;
@property (nonatomic, copy) NSString * _Nonnull siteUrl;
@property (nonatomic, copy) NSString * _Nonnull supportFacebookLogin;
@property (nonatomic, copy) NSString * _Nonnull supportOtp;
@property (nonatomic, copy) NSString * _Nonnull supportSocialMediaSharing;
@property (nonatomic, copy) NSString * _Nonnull welcomeVideoUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk10ClientInfo")
@interface ClientInfo : YuppModel
@property (nonatomic, copy) NSString * _Nonnull versionNumber;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull server;
@property (nonatomic, copy) NSString * _Nonnull clientInfoDescription;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull params;
@property (nonatomic) NSInteger updateType;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk13CloseCaptions")
@interface CloseCaptions : YuppModel
@property (nonatomic, copy) NSArray<CCData *> * _Nonnull ccList;
@property (nonatomic, copy) NSString * _Nonnull defaultLang;
@property (nonatomic, copy) NSString * _Nonnull loadDefault;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<CCData *> * _Nonnull)ccListWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk6Config")
@interface Config : YuppModel
@property (nonatomic) BOOL isOTPSupported;
@property (nonatomic) BOOL isSocialMediaSharingSupported;
@property (nonatomic) BOOL supportChromecast;
@property (nonatomic) BOOL isFacebookLoginSupported;
@property (nonatomic, copy) NSString * _Nonnull siteURL;
@property (nonatomic) NSInteger maxOTPLength;
@property (nonatomic, copy) NSString * _Nonnull primaryTimeZone;
@property (nonatomic, copy) NSString * _Nonnull primaryTimeZoneOffset;
@property (nonatomic, copy) NSString * _Nonnull callingNumber;
@property (nonatomic) BOOL isCallSupported;
@property (nonatomic) BOOL supportGoogleLogin;
@property (nonatomic) BOOL supportAppleLogin;
@property (nonatomic) BOOL iosAllowSignup;
@property (nonatomic, copy) NSString * _Nonnull buttonRecord;
@property (nonatomic, copy) NSString * _Nonnull buttonStopRecord;
@property (nonatomic, copy) NSString * _Nonnull recordStatusRecorded;
@property (nonatomic, copy) NSString * _Nonnull recordStatusRecording;
@property (nonatomic, copy) NSString * _Nonnull recordStatusScheduled;
@property (nonatomic) BOOL enableNdvr;
@property (nonatomic) BOOL supportBannerAds;
@property (nonatomic) BOOL supportInterstitialAds;
@property (nonatomic) BOOL supportNativeAds;
@property (nonatomic, copy) NSString * _Nonnull BannerAdUnitId;
@property (nonatomic, copy) NSString * _Nonnull NativeAdUnitId;
@property (nonatomic, copy) NSString * _Nonnull validMobileRegex;
@property (nonatomic) BOOL supportLocalytics;
@property (nonatomic) BOOL supportFirebase;
@property (nonatomic) BOOL supportCleverTap;
@property (nonatomic, copy) NSString * _Nonnull lmsEntryUrl;
@property (nonatomic) NSInteger nextVideoDisplayPercentage;
@property (nonatomic) NSInteger nextVideoDisplaySeconds;
@property (nonatomic, copy) NSString * _Nonnull nextVideoDisplayType;
@property (nonatomic, copy) NSString * _Nonnull aboutUsPageUrl;
@property (nonatomic, copy) NSString * _Nonnull contactUsPageUrl;
@property (nonatomic, copy) NSString * _Nonnull faqPageUrl;
@property (nonatomic, copy) NSString * _Nonnull privacyPolicyPageUrl;
@property (nonatomic, copy) NSString * _Nonnull termsConditionsPageUrl;
@property (nonatomic, copy) NSString * _Nonnull helpPageUrl;
@property (nonatomic, copy) NSString * _Nonnull resSErrorNeedPaymentIos;
@property (nonatomic, copy) NSString * _Nonnull resSErrorNotLoggedInIos;
@property (nonatomic, copy) NSString * _Nonnull signinTitle;
@property (nonatomic, copy) NSString * _Nonnull signupTitle;
@property (nonatomic, copy) NSString * _Nonnull activeScreensTitleFromPlayer;
@property (nonatomic, copy) NSString * _Nonnull activeScreensTitleFromSettings;
@property (nonatomic, copy) NSString * _Nonnull webPaymentUpgradeMessage;
@property (nonatomic, copy) NSString * _Nonnull amazonPaymentUpgradeMessage;
@property (nonatomic, copy) NSString * _Nonnull rokuPaymentUpgradeMessage;
@property (nonatomic, copy) NSString * _Nonnull allowedCountriesList;
@property (nonatomic, copy) NSString * _Nonnull iosBuyMessage;
@property (nonatomic, copy) NSString * _Nonnull helpJsonString;
@property (nonatomic, copy) NSString * _Nonnull megaMenuSections;
@property (nonatomic, copy) NSString * _Nonnull noPlanButtonText;
@property (nonatomic, copy) NSString * _Nonnull noPlanMessageText;
@property (nonatomic, copy) NSString * _Nonnull noPlanMessageDescription;
@property (nonatomic, copy) NSString * _Nonnull basicPlanButtonText;
@property (nonatomic, copy) NSString * _Nonnull basicPlanMessageText;
@property (nonatomic, copy) NSString * _Nonnull basicPlanMessageDescription;
@property (nonatomic) BOOL playLastChannelOnLaunch;
@property (nonatomic) NSInteger maxdvrtime;
@property (nonatomic, copy) NSString * _Nonnull maxDvrDisplayText;
@property (nonatomic, copy) NSString * _Nonnull startOverTextMessage;
@property (nonatomic) BOOL showStreamBitRate;
@property (nonatomic, copy) NSString * _Nonnull tvshowPlayerRecommendationText;
@property (nonatomic, copy) NSString * _Nonnull tvshowDetailsRecommendationText;
@property (nonatomic, copy) NSString * _Nonnull movieDetailsRecommendationText;
@property (nonatomic, copy) NSString * _Nonnull moviePlayerRecommendationText;
@property (nonatomic, copy) NSString * _Nonnull channelRecommendationText;
@property (nonatomic, copy) NSString * _Nonnull favouritesTargetPath;
@property (nonatomic, copy) NSString * _Nonnull myPurchasesTargetPathMobiles;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class LanguageSelectinoAttributes;
@class Language;
@class ResourceProfile;
@class Menu;

SWIFT_CLASS("_TtC6OTTSdk14ConfigResponse")
@interface ConfigResponse : YuppModel
@property (nonatomic, strong) ClientConfig * _Nonnull clientConfigs;
@property (nonatomic, strong) LanguageSelectinoAttributes * _Nonnull languageSelectionAttributes;
@property (nonatomic, copy) NSArray<Language *> * _Nonnull displayLanguages;
@property (nonatomic, strong) Config * _Nonnull configs;
@property (nonatomic, copy) NSArray<Language *> * _Nonnull contentLanguages;
@property (nonatomic, copy) NSArray<ResourceProfile *> * _Nonnull resourceProfiles;
@property (nonatomic, copy) NSArray<Menu *> * _Nonnull menus;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull rawData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Menu *> * _Nonnull)menusWithJson:(id _Nonnull)json SWIFT_WARN_UNUSED_RESULT;
@end

@class DataRow;

SWIFT_CLASS("_TtC6OTTSdk7Content")
@interface Content : YuppModel
@property (nonatomic, copy) NSString * _Nonnull backgroundImage;
@property (nonatomic, copy) NSString * _Nonnull contentDescription;
@property (nonatomic, copy) NSArray<DataRow *> * _Nonnull dataRows;
@property (nonatomic, copy) NSString * _Nonnull posterImage;
@property (nonatomic, copy) NSString * _Nonnull title;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6OTTSdk7Country")
@interface Country : YuppModel
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger isdCode;
@property (nonatomic, copy) NSString * _Nonnull iconUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Country *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

@class Element;

SWIFT_CLASS("_TtC6OTTSdk7DataRow")
@interface DataRow : YuppModel
@property (nonatomic, copy) NSArray<Element *> * _Nonnull elements;
@property (nonatomic, copy) NSString * _Nonnull rowDataType;
@property (nonatomic) NSInteger rowNumber;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6OTTSdk7Details")
@interface Details : YuppModel
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSString * _Nonnull referenceId;
@property (nonatomic, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, copy) NSString * _Nonnull errorDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

SWIFT_CLASS("_TtC6OTTSdk6Device")
@interface Device : YuppModel
@property (nonatomic, copy) NSString * _Nonnull boxId;
@property (nonatomic) NSInteger deviceId;
@property (nonatomic) BOOL isCurrentDevice;
@property (nonatomic, strong) NSNumber * _Nonnull loggedinTime;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Device *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk7Display")
@interface Display : YuppModel
@property (nonatomic, copy) NSString * _Nonnull subtitle1;
@property (nonatomic, copy) NSString * _Nonnull subtitle2;
@property (nonatomic, copy) NSString * _Nonnull subtitle3;
@property (nonatomic, copy) NSString * _Nonnull subtitle4;
@property (nonatomic, copy) NSString * _Nonnull subtitle5;
@property (nonatomic, copy) NSString * _Nonnull parentIcon;
@property (nonatomic, copy) NSString * _Nonnull parentName;
@property (nonatomic, copy) NSString * _Nonnull layout;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
@property (nonatomic) BOOL isRecording;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk7Element")
@interface Element : YuppModel
@property (nonatomic, copy) NSString * _Nonnull elementSubtype;
@property (nonatomic, copy) NSString * _Nonnull elementCode;
@property (nonatomic, copy) NSString * _Nonnull contentCode;
@property (nonatomic, copy) NSString * _Nonnull data;
@property (nonatomic, copy) NSString * _Nonnull color;
@property (nonatomic, copy) NSString * _Nonnull bgColor;
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull target;
@property (nonatomic) BOOL isClickable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UserFeedbackRecord;

SWIFT_CLASS("_TtC6OTTSdk8Feedback")
@interface Feedback : YuppModel
@property (nonatomic) BOOL feedbackAllowed;
@property (nonatomic) BOOL showFeedback;
@property (nonatomic, strong) UserFeedbackRecord * _Nullable userFeedbackRecord;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class FilterItem;

SWIFT_CLASS("_TtC6OTTSdk6Filter")
@interface Filter : YuppModel
@property (nonatomic) BOOL selectableSortDirection;
@property (nonatomic, copy) NSArray<FilterItem *> * _Nonnull items;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic) BOOL multiSelectable;
@property (nonatomic) BOOL isSort;
@property (nonatomic, copy) NSString * _Nonnull title;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Filter *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk10FilterItem")
@interface FilterItem : YuppModel
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull image;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<FilterItem *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

@class Property;

SWIFT_CLASS("_TtC6OTTSdk11FormElement")
@interface FormElement : YuppModel
@property (nonatomic, copy) NSString * _Nonnull data;
@property (nonatomic) NSInteger rowNumber;
@property (nonatomic, copy) NSString * _Nonnull elementCode;
@property (nonatomic) NSInteger columnSpan;
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull formCode;
@property (nonatomic) NSInteger columnNumber;
@property (nonatomic) NSInteger rowSpan;
@property (nonatomic, copy) NSString * _Nonnull fieldType;
@property (nonatomic, copy) NSString * _Nonnull value;
@property (nonatomic, strong) Property * _Nonnull properties;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<FormElement *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk8FormInfo")
@interface FormInfo : YuppModel
@property (nonatomic, copy) NSString * _Nonnull regex;
@property (nonatomic, copy) NSString * _Nonnull value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk14InfoAttributes")
@interface InfoAttributes : YuppModel
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, strong) NSNumber * _Nonnull endTime;
@property (nonatomic) BOOL isLive;
@property (nonatomic, strong) NSNumber * _Nonnull startTime;
@property (nonatomic) BOOL isRecorded;
@property (nonatomic, copy) NSString * _Nonnull recordingForm;
@property (nonatomic) BOOL isRecordingAllowed;
@property (nonatomic, strong) NSNumber * _Nonnull takeaTestStartTime;
@property (nonatomic, copy) NSString * _Nonnull takeaTestURL;
@property (nonatomic) double watchedPosition;
@property (nonatomic, copy) NSString * _Nonnull playerType;
@property (nonatomic, copy) NSString * _Nonnull nextButtonTitle;
@property (nonatomic, copy) NSString * _Nonnull showNextButton;
@property (nonatomic, copy) NSString * _Nonnull recommendationText;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk6IpInfo")
@interface IpInfo : YuppModel
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull continentCode;
@property (nonatomic, copy) NSString * _Nonnull latitude;
@property (nonatomic, copy) NSString * _Nonnull continentName;
@property (nonatomic, copy) NSString * _Nonnull timezone;
@property (nonatomic, copy) NSString * _Nonnull trueIP;
@property (nonatomic, copy) NSString * _Nonnull country;
@property (nonatomic, copy) NSString * _Nonnull longitude;
@property (nonatomic, copy) NSString * _Nonnull postalCode;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, copy) NSString * _Nonnull region;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk8Language")
@interface Language : YuppModel
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Language *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk27LanguageSelectinoAttributes")
@interface LanguageSelectinoAttributes : YuppModel
@property (nonatomic) BOOL forceSelection;
@property (nonatomic) BOOL isMultiSelectable;
@property (nonatomic) BOOL isEmailVerified;
@property (nonatomic) BOOL maxSelectable;
@property (nonatomic) BOOL minSelectable;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk21LocationAnalyticsInfo")
@interface LocationAnalyticsInfo : YuppModel
@property (nonatomic, copy) NSString * _Nonnull authKey;
@property (nonatomic, copy) NSString * _Nonnull analyticsId;
@property (nonatomic, strong) NSNumber * _Nonnull serverTime;
@property (nonatomic, strong) NSNumber * _Nonnull hbRateInMillis;
@property (nonatomic, copy) NSString * _Nonnull collectorAPI;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class ProductInfo;

SWIFT_CLASS("_TtC6OTTSdk20LocationinfoResponse")
@interface LocationinfoResponse : YuppModel
@property (nonatomic, strong) IpInfo * _Nonnull ipInfo;
@property (nonatomic, strong) ProductInfo * _Nonnull productInfo;
@property (nonatomic, strong) ClientInfo * _Nonnull clientInfo;
@property (nonatomic, strong) LocationAnalyticsInfo * _Nonnull analyticsInfo;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull rawData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk19MediaCatalogManager")
@interface MediaCatalogManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SubMenu;

SWIFT_CLASS("_TtC6OTTSdk4Menu")
@interface Menu : YuppModel
@property (nonatomic, copy) NSString * _Nonnull menuDescription;
@property (nonatomic, copy) NSArray<SubMenu *> * _Nullable subMenus;
@property (nonatomic, copy) NSString * _Nonnull displayText;
@property (nonatomic) BOOL isClickable;
@property (nonatomic, copy) NSString * _Nonnull targetPath;
@property (nonatomic, copy) NSString * _Nonnull code;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Menu *> * _Nonnull)menusWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk8Metadata")
@interface Metadata : YuppModel
@property (nonatomic, copy) NSString * _Nonnull id;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk11MyQuestions")
@interface MyQuestions : YuppModel
@property (nonatomic, copy) NSString * _Nonnull question;
@property (nonatomic, strong) NSNumber * _Nonnull postedTime;
@property (nonatomic, strong) NSNumber * _Nonnull lastUpdatedTime;
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nonnull lastUpdatedBy;
@property (nonatomic) NSInteger status;
@property (nonatomic, copy) NSString * _Nonnull attachmentPath;
@property (nonatomic) NSInteger contentId;
@property (nonatomic) NSInteger userId;
@property (nonatomic) BOOL fromModerator;
@property (nonatomic) BOOL hasAttachment;
@property (nonatomic, copy) NSString * _Nonnull userName;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<MyQuestions *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk19MyQuestionsResponse")
@interface MyQuestionsResponse : YuppModel
@property (nonatomic, copy) NSString * _Nonnull genre;
@property (nonatomic, copy) NSString * _Nonnull chapterName;
@property (nonatomic, copy) NSArray<MyQuestions *> * _Nonnull questions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk3OTP")
@interface OTP : YuppModel
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic) NSInteger referenceId;
@property (nonatomic) NSInteger statusCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk6OTTSdk")
@interface OTTSdk : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6OTTSdk7Package")
@interface Package : YuppModel
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, strong) NSNumber * _Nonnull purchaseDate;
@property (nonatomic, strong) NSNumber * _Nonnull expiryDate;
@property (nonatomic, copy) NSString * _Nonnull packageType;
@property (nonatomic) NSInteger id;
@property (nonatomic, copy) NSString * _Nonnull gateway;
@property (nonatomic) BOOL isRecurring;
@property (nonatomic) BOOL isUnSubscribed;
@property (nonatomic) NSInteger isCurrentlyActivePlan;
@property (nonatomic) NSInteger changePlanAvailable;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull gatewayName;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic) float packageAmount;
@property (nonatomic) float saleAmount;
@property (nonatomic) NSInteger points;
@property (nonatomic, copy) NSString * _Nonnull effectiveFrom;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Package *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk14PageAttributes")
@interface PageAttributes : YuppModel
@property (nonatomic, copy) NSString * _Nonnull startTime;
@property (nonatomic, copy) NSString * _Nonnull endTime;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nonnull recordingForm;
@property (nonatomic) BOOL isRecordingAllowed;
@property (nonatomic) BOOL isRecorded;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class Record;

SWIFT_CLASS("_TtC6OTTSdk11PageButtons")
@interface PageButtons : YuppModel
@property (nonatomic) BOOL isFavourite;
@property (nonatomic) BOOL showFavouriteButton;
@property (nonatomic, strong) Record * _Nullable record;
@property (nonatomic, strong) Feedback * _Nullable feedback;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class PageInfo;
@class PageEventInfo;
@class PageData;
@class TabsInfo;
@class ShareInfo;
@class StreamStatus;

SWIFT_CLASS("_TtC6OTTSdk19PageContentResponse")
@interface PageContentResponse : YuppModel
@property (nonatomic, strong) PageInfo * _Nonnull info;
@property (nonatomic, copy) NSArray<Banner *> * _Nonnull banners;
@property (nonatomic, copy) NSArray<PageEventInfo *> * _Nonnull pageEventInfo;
@property (nonatomic) id _Nullable promoBanners;
@property (nonatomic, copy) NSArray<PageData *> * _Nonnull data;
@property (nonatomic, copy) NSArray<Filter *> * _Nonnull filters;
@property (nonatomic, strong) TabsInfo * _Nonnull tabsInfo;
@property (nonatomic, strong) ShareInfo * _Nonnull shareInfo;
@property (nonatomic, strong) StreamStatus * _Nonnull streamStatus;
@property (nonatomic, strong) PageButtons * _Nonnull pageButtons;
@property (nonatomic, strong) AdUrlResponse * _Nonnull adUrlResponse;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk8PageData")
@interface PageData : YuppModel
@property (nonatomic) id _Nullable paneData;
@property (nonatomic) NSInteger adPositionIndex;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<PageData *> * _Nonnull)dataWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

@class TargetParams;

SWIFT_CLASS("_TtC6OTTSdk13PageEventInfo")
@interface PageEventInfo : YuppModel
@property (nonatomic, copy) NSString * _Nonnull targetPath;
@property (nonatomic, strong) TargetParams * _Nonnull targetParams;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<PageEventInfo *> * _Nonnull)pageEventInfoWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk8PageInfo")
@interface PageInfo : YuppModel
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull path;
@property (nonatomic, strong) InfoAttributes * _Nonnull attributes;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk15PaymentsManager")
@interface PaymentsManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk8Position")
@interface Position : YuppModel
@property (nonatomic, copy) NSString * _Nonnull interval;
@property (nonatomic, copy) NSString * _Nonnull maxCount;
@property (nonatomic, copy) NSString * _Nonnull show;
@property (nonatomic, copy) NSString * _Nonnull offset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk17PreferenceManager")
@interface PreferenceManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6OTTSdk11ProductInfo")
@interface ProductInfo : YuppModel
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class ProgramTarget;

SWIFT_CLASS("_TtC6OTTSdk7Program")
@interface Program : YuppModel
@property (nonatomic, strong) TVGuideDisplay * _Nonnull display;
@property (nonatomic, strong) ProgramTarget * _Nonnull target;
@property (nonatomic, strong) Metadata * _Nonnull metadata;
@property (nonatomic) NSInteger programID;
@property (nonatomic, copy, getter=template, setter=setTemplate:) NSString * _Nonnull template_;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Program *> * _Nonnull)programsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk13ProgramTarget")
@interface ProgramTarget : YuppModel
@property (nonatomic, copy) NSString * _Nonnull path;
@property (nonatomic, strong) PageAttributes * _Nonnull pageAttributes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk8Property")
@interface Property : YuppModel
@property (nonatomic, copy) NSString * _Nonnull group_id;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk8Question")
@interface Question : YuppModel
@property (nonatomic, copy) NSString * _Nonnull question;
@property (nonatomic, strong) NSNumber * _Nonnull postedTime;
@property (nonatomic, copy) NSString * _Nonnull contentType;
@property (nonatomic, copy) NSString * _Nonnull contentId;
@property (nonatomic) NSInteger userId;
@property (nonatomic, copy) NSString * _Nonnull userName;
@property (nonatomic) NSInteger status;
@property (nonatomic, copy) NSString * _Nonnull attachmentPath;
@property (nonatomic) BOOL hasAttachment;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Question *> * _Nonnull)questionsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk29QuestionGenresContentResponse")
@interface QuestionGenresContentResponse : YuppModel
@property (nonatomic, copy) NSArray * _Nonnull contentNameData;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk22QuestionGenresResponse")
@interface QuestionGenresResponse : YuppModel
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull genreArray;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk6Record")
@interface Record : YuppModel
@property (nonatomic, copy) NSString * _Nonnull buttonText;
@property (nonatomic, copy) NSString * _Nonnull channelId;
@property (nonatomic) BOOL isRecorded;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk21RecordingFormResponse")
@interface RecordingFormResponse : YuppModel
@property (nonatomic, copy) NSString * _Nonnull path;
@property (nonatomic, copy) NSString * _Nonnull backgroundImage;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSArray<FormElement *> * _Nonnull elements;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk15ResourceProfile")
@interface ResourceProfile : YuppModel
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic) BOOL isDefault;
@property (nonatomic, copy) NSString * _Nonnull urlPrefix;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<ResourceProfile *> * _Nonnull)resourceProfilesWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

@class TemplateElement;

SWIFT_CLASS("_TtC6OTTSdk3Row")
@interface Row : YuppModel
@property (nonatomic, copy) NSString * _Nonnull rowDataType;
@property (nonatomic) NSInteger rowNumber;
@property (nonatomic, copy) NSArray<TemplateElement *> * _Nonnull templateElements;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Row *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk14SearchResponse")
@interface SearchResponse : YuppModel
@property (nonatomic, copy) NSString * _Nonnull sourceType;
@property (nonatomic, copy) NSString * _Nonnull displayName;
@property (nonatomic) NSInteger count;
@property (nonatomic, copy) NSArray<Card *> * _Nonnull data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<SearchResponse *> * _Nonnull)searchArrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

@class SectionInfo;
@class SectionData;
@class SectionControls;

SWIFT_CLASS("_TtC6OTTSdk7Section")
@interface Section : YuppModel
@property (nonatomic, strong) SectionInfo * _Nonnull sectionInfo;
@property (nonatomic, strong) SectionData * _Nonnull sectionData;
@property (nonatomic, strong) SectionControls * _Nonnull sectionControls;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk15SectionControls")
@interface SectionControls : YuppModel
@property (nonatomic) BOOL showViewAll;
@property (nonatomic, copy) NSString * _Nonnull viewAllTargetPath;
@property (nonatomic) BOOL infiniteScroll;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk11SectionData")
@interface SectionData : YuppModel
@property (nonatomic, copy) NSString * _Nonnull section;
@property (nonatomic, copy) NSArray<Card *> * _Nonnull data;
@property (nonatomic) NSInteger lastIndex;
@property (nonatomic) BOOL hasMoreData;
@property (nonatomic) NSInteger dataRequestDelay;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<SectionData *> * _Nonnull)sectionsDataListWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk11SectionInfo")
@interface SectionInfo : YuppModel
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull sectionDescription;
@property (nonatomic, copy) NSString * _Nonnull dataSubType;
@property (nonatomic, copy) NSString * _Nonnull bannerImage;
@property (nonatomic) BOOL showLanguageFilter;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic) NSInteger id;
@property (nonatomic) BOOL showGenreFilter;
@property (nonatomic, copy) NSString * _Nonnull dataType;
@property (nonatomic, copy) NSString * _Nonnull iconUrl;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk11SessionInfo")
@interface SessionInfo : YuppModel
@property (nonatomic) NSInteger pollIntervalInMillis;
@property (nonatomic, copy) NSString * _Nonnull streamPollKey;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk9ShareInfo")
@interface ShareInfo : YuppModel
@property (nonatomic, copy) NSString * _Nonnull shareDescription;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
@property (nonatomic) BOOL isSharingAllowed;
@property (nonatomic, copy) NSString * _Nonnull name;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class User;

SWIFT_CLASS("_TtC6OTTSdk18SignInValidateInfo")
@interface SignInValidateInfo : YuppModel
@property (nonatomic, readonly) NSInteger actionCode;
@property (nonatomic, readonly, strong) User * _Nullable userDetails;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SignupValidationDetails;

SWIFT_CLASS("_TtC6OTTSdk18SignupValidateInfo")
@interface SignupValidateInfo : YuppModel
@property (nonatomic, readonly) NSInteger actionCode;
@property (nonatomic, readonly, strong) SignupValidationDetails * _Nullable details;
@property (nonatomic, readonly, strong) User * _Nullable userDetails;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk23SignupValidationDetails")
@interface SignupValidationDetails : YuppModel
@property (nonatomic, copy) NSString * _Nonnull referenceKey;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic, copy) NSString * _Nonnull mobile;
@property (nonatomic, copy) NSString * _Nonnull message;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk20StaticContentManager")
@interface StaticContentManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk6Stream")
@interface Stream : YuppModel
@property (nonatomic) BOOL isDefault;
@property (nonatomic, copy) NSString * _Nonnull streamType;
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic, strong) CloseCaptions * _Nonnull closeCaptions;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Stream *> * _Nonnull)streamsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end

@class UserLocation;

SWIFT_CLASS("_TtC6OTTSdk19StreamActiveSession")
@interface StreamActiveSession : YuppModel
@property (nonatomic, copy) NSString * _Nonnull deviceName;
@property (nonatomic, copy) NSString * _Nonnull deviceIconUrl;
@property (nonatomic, strong) NSNumber * _Nonnull lastUpdatedTime;
@property (nonatomic, strong) UserLocation * _Nonnull userLocation;
@property (nonatomic, copy) NSString * _Nonnull boxId;
@property (nonatomic, copy) NSString * _Nonnull tenantCode;
@property (nonatomic, copy) NSString * _Nonnull streamPollKey;
@property (nonatomic, copy) NSString * _Nonnull deviceSubtype;
@property (nonatomic) NSInteger deviceId;
@property (nonatomic, copy) NSString * _Nonnull appSessionId;
@property (nonatomic, copy) NSString * _Nonnull productCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<StreamActiveSession *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk14StreamResponse")
@interface StreamResponse : YuppModel
@property (nonatomic) NSInteger count;
@property (nonatomic, strong) SessionInfo * _Nonnull sessionInfo;
@property (nonatomic) NSInteger maxBitrateAllowed;
@property (nonatomic, copy) NSArray<Stream *> * _Nonnull streams;
@property (nonatomic, strong) StreamStatus * _Nonnull streamStatus;
@property (nonatomic, strong) AnalyticsInfo * _Nonnull analyticsInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk12StreamStatus")
@interface StreamStatus : YuppModel
@property (nonatomic) BOOL hasAccess;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic) NSInteger seekPositionInMillis;
@property (nonatomic) NSInteger totalDurationInMillis;
@property (nonatomic) NSInteger errorCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk7SubMenu")
@interface SubMenu : YuppModel
@property (nonatomic, copy) NSString * _Nonnull menuDescription;
@property (nonatomic, copy) NSArray * _Nullable subMenus;
@property (nonatomic, copy) NSString * _Nonnull displayText;
@property (nonatomic) BOOL isClickable;
@property (nonatomic, copy) NSString * _Nonnull targetPath;
@property (nonatomic, copy) NSString * _Nonnull code;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<SubMenu *> * _Nonnull)submenusWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk14TVGuideDisplay")
@interface TVGuideDisplay : YuppModel
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull imageUrl;
@property (nonatomic, copy) NSString * _Nonnull subtitle1;
@property (nonatomic, copy) NSString * _Nonnull subtitle2;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class TVGuideTab;

SWIFT_CLASS("_TtC6OTTSdk15TVGuideResponse")
@interface TVGuideResponse : YuppModel
@property (nonatomic, copy) NSString * _Nonnull tiltle;
@property (nonatomic, copy) NSArray<TVGuideTab *> * _Nonnull tabs;
@property (nonatomic, copy) NSArray<ChannelObj *> * _Nonnull data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk10TVGuideTab")
@interface TVGuideTab : YuppModel
@property (nonatomic, copy) NSString * _Nonnull subtitle;
@property (nonatomic, strong) NSNumber * _Nonnull startTime;
@property (nonatomic, strong) NSNumber * _Nonnull endTime;
@property (nonatomic) BOOL isSelected;
@property (nonatomic, copy) NSString * _Nonnull title;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<TVGuideTab *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk3Tab")
@interface Tab : YuppModel
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull sectionCodes;
@property (nonatomic) BOOL infiniteScroll;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Tab *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk8TabsInfo")
@interface TabsInfo : YuppModel
@property (nonatomic) BOOL showTabs;
@property (nonatomic, copy) NSString * _Nonnull hints;
@property (nonatomic, copy) NSArray<Tab *> * _Nonnull tabs;
@property (nonatomic, copy) NSString * _Nonnull selectedTab;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk12TargetParams")
@interface TargetParams : YuppModel
@property (nonatomic) BOOL autoRedirect;
@property (nonatomic, copy) NSString * _Nonnull buttonText;
@property (nonatomic) BOOL isDefault;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end

@class TemplateDataObj;

SWIFT_CLASS("_TtC6OTTSdk12TemplateData")
@interface TemplateData : YuppModel
@property (nonatomic, copy) NSString * _Nonnull templateCode;
@property (nonatomic, strong) TemplateDataObj * _Nonnull data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk15TemplateDataObj")
@interface TemplateDataObj : YuppModel
@property (nonatomic, copy) NSString * _Nonnull target_description;
@property (nonatomic, copy) NSString * _Nonnull description_property;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull show_description;
@property (nonatomic, copy) NSString * _Nonnull show_name;
@property (nonatomic, copy) NSString * _Nonnull description_;
@property (nonatomic, copy) NSString * _Nonnull name_property;
@property (nonatomic, copy) NSString * _Nonnull target_name;
@property (nonatomic, copy) NSString * _Nonnull value_name;
@property (nonatomic, copy) NSString * _Nonnull value_description;
@property (nonatomic, copy) NSString * _Nonnull target_watch_latest_episode;
@property (nonatomic, copy) NSString * _Nonnull duration;
@property (nonatomic, copy) NSString * _Nonnull resume;
@property (nonatomic, copy) NSString * _Nonnull image;
@property (nonatomic, copy) NSString * _Nonnull target_resume;
@property (nonatomic, copy) NSString * _Nonnull target_browse_episodes;
@property (nonatomic) BOOL show_watch_latest_episode;
@property (nonatomic) BOOL show_image;
@property (nonatomic) BOOL show_duration;
@property (nonatomic) BOOL show_resume;
@property (nonatomic) BOOL show_browse_episodes;
@property (nonatomic) float watchedPosition;
@property (nonatomic, copy) NSString * _Nonnull target_watchnow;
@property (nonatomic, copy) NSString * _Nonnull cast;
@property (nonatomic) BOOL show_watchnow;
@property (nonatomic) BOOL show_subtitle;
@property (nonatomic) BOOL show_cast;
@property (nonatomic, copy) NSString * _Nonnull subtitle;
@property (nonatomic, copy) NSString * _Nonnull show_startover;
@property (nonatomic, copy) NSString * _Nonnull target_startover;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull rawData;
@property (nonatomic) BOOL show_startover_live;
@property (nonatomic) BOOL show_delete_record;
@property (nonatomic) BOOL show_expires;
@property (nonatomic) BOOL show_watchlive;
@property (nonatomic) BOOL show_stop_record;
@property (nonatomic) BOOL show_available_soon;
@property (nonatomic) BOOL show_expiry;
@property (nonatomic) BOOL show_startover_past;
@property (nonatomic) BOOL show_record_upgrade;
@property (nonatomic) BOOL show_record;
@property (nonatomic, copy) NSString * _Nonnull target_startover_past;
@property (nonatomic, copy) NSString * _Nonnull expires;
@property (nonatomic, copy) NSString * _Nonnull target_watchlive;
@property (nonatomic, copy) NSString * _Nonnull target_startover_live;
@property (nonatomic, strong) NSNumber * _Nonnull expiryTime;
@property (nonatomic) BOOL show_expires_today;
@property (nonatomic) BOOL show_stream_not_available;
@property (nonatomic) BOOL show_available_soon_label;
@property (nonatomic) BOOL show_expires_day;
@property (nonatomic, copy) NSString * _Nonnull expires_day;
@property (nonatomic) BOOL show_subscribe;
@property (nonatomic, copy) NSString * _Nonnull show_available_soon_record;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk15TemplateElement")
@interface TemplateElement : YuppModel
@property (nonatomic, copy) NSString * _Nonnull elementSubtype;
@property (nonatomic, copy) NSString * _Nonnull contentCode;
@property (nonatomic, copy) NSString * _Nonnull data;
@property (nonatomic) NSInteger rowNumber;
@property (nonatomic, copy) NSString * _Nonnull elementCode;
@property (nonatomic) NSInteger columnSpan;
@property (nonatomic, copy) NSString * _Nonnull displayCondition;
@property (nonatomic) NSInteger id;
@property (nonatomic) NSInteger columnNumber;
@property (nonatomic) NSInteger rowSpan;
@property (nonatomic, copy) NSString * _Nonnull target;
@property (nonatomic, copy) NSString * _Nonnull elementType;
@property (nonatomic, copy) NSString * _Nonnull value;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<TemplateElement *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk16TemplateResponse")
@interface TemplateResponse : YuppModel
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull backgroundImage;
@property (nonatomic, copy) NSArray<Row *> * _Nonnull rows;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<TemplateResponse *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk11Transaction")
@interface Transaction : YuppModel
@property (nonatomic, copy) NSString * _Nonnull orderId;
@property (nonatomic, copy) NSString * _Nonnull packageName;
@property (nonatomic, strong) NSNumber * _Nonnull expiryTime;
@property (nonatomic, copy) NSString * _Nonnull amount;
@property (nonatomic, copy) NSString * _Nonnull status;
@property (nonatomic, copy) NSString * _Nonnull currency;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic, strong) NSNumber * _Nonnull purchaseTime;
@property (nonatomic, copy) NSString * _Nonnull gateway;
@property (nonatomic, copy) NSString * _Nonnull tax;
@property (nonatomic, copy) NSString * _Nonnull totalAmount;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<Transaction *> * _Nonnull)arrayWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk4User")
@interface User : YuppModel <NSCoding>
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull languages;
@property (nonatomic, copy) NSString * _Nonnull phoneNumber;
@property (nonatomic, copy) NSString * _Nonnull email;
@property (nonatomic) BOOL isEmailVerified;
@property (nonatomic) NSInteger status;
@property (nonatomic, copy) NSString * _Nonnull message;
@property (nonatomic) NSInteger userId;
@property (nonatomic) BOOL isPhoneNumberVerified;
@property (nonatomic, copy) NSArray * _Nonnull packages;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull rawData;
@property (nonatomic, strong) Attributes * _Nonnull attributes;
@property (nonatomic, copy) NSString * _Nonnull firstName;
@property (nonatomic, copy) NSString * _Nonnull lastName;
@property (nonatomic, strong) NSNumber * _Nonnull dob;
@property (nonatomic, copy) NSString * _Nonnull gender;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end


SWIFT_CLASS("_TtC6OTTSdk18UserFeedbackRecord")
@interface UserFeedbackRecord : YuppModel
@property (nonatomic) NSInteger rating;
@property (nonatomic, copy) NSString * _Nonnull feedBackDescription;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk15UserFormElement")
@interface UserFormElement : YuppModel
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) NSInteger priority;
@property (nonatomic, copy) NSString * _Nonnull nextForm;
@property (nonatomic) BOOL isMandatory;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic) NSInteger formID;
@property (nonatomic, copy) NSString * _Nonnull formCode;
@property (nonatomic, copy) NSString * _Nonnull fieldType;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
@property (nonatomic, strong) FormInfo * _Nonnull info;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<UserFormElement *> * _Nonnull)formElementsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk12UserLocation")
@interface UserLocation : YuppModel
@property (nonatomic, copy) NSString * _Nonnull city;
@property (nonatomic, copy) NSString * _Nonnull continentCode;
@property (nonatomic, copy) NSString * _Nonnull ip;
@property (nonatomic, copy) NSString * _Nonnull state;
@property (nonatomic, copy) NSString * _Nonnull timezone;
@property (nonatomic, copy) NSString * _Nonnull country;
@property (nonatomic, copy) NSString * _Nonnull postalCode;
@property (nonatomic, copy) NSString * _Nonnull repCountryCode;
@property (nonatomic, copy) NSString * _Nonnull countryCode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk11UserManager")
@interface UserManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC6OTTSdk11UserProgram")
@interface UserProgram : YuppModel
@property (nonatomic) NSInteger programId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<UserProgram *> * _Nonnull)userProgramsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6OTTSdk19UserProgramResponse")
@interface UserProgramResponse : YuppModel
@property (nonatomic) NSInteger channelId;
@property (nonatomic, copy) NSArray<UserProgram *> * _Nonnull programs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init:(NSDictionary<NSString *, id> * _Nonnull)json OBJC_DESIGNATED_INITIALIZER;
+ (NSArray<UserProgramResponse *> * _Nonnull)userChannelProgramsWithJson:(id _Nullable)json SWIFT_WARN_UNUSED_RESULT;
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
